In [1]:
import pandas as pd
import numpy as np
data = {
'Order_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
'Customer_Name': ['Amara', 'Bola', None, 'Diana', 'Efua', 'Fatima', 'Grace',
None, 'Ifeoma', 'Joyce'],
'Country': ['Ghana', 'Nigeria', 'Kenya', None, 'Ghana', 'Cameroon', None,
'Kenya', 'Nigeria', 'Ghana'],
'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', None, 'Phone', 'Tablet',
'Laptop', None, 'Phone'],
'Quantity': [2, 1, None, 3, 2, None, 1, 4, 2, None],
'Price': [1500, 800, 600, 1500, None, 800, 600, 1500, None, 800],
'Delivery_Days': [3, None, 7, 5, 3, None, 6, None, 4, 5]
}
df = pd.DataFrame(data)
print(df)

   Order_ID Customer_Name   Country Product  Quantity   Price  Delivery_Days
0       101         Amara     Ghana  Laptop       2.0  1500.0            3.0
1       102          Bola   Nigeria   Phone       1.0   800.0            NaN
2       103           NaN     Kenya  Tablet       NaN   600.0            7.0
3       104         Diana       NaN  Laptop       3.0  1500.0            5.0
4       105          Efua     Ghana     NaN       2.0     NaN            3.0
5       106        Fatima  Cameroon   Phone       NaN   800.0            NaN
6       107         Grace       NaN  Tablet       1.0   600.0            6.0
7       108           NaN     Kenya  Laptop       4.0  1500.0            NaN
8       109        Ifeoma   Nigeria     NaN       2.0     NaN            4.0
9       110         Joyce     Ghana   Phone       NaN   800.0            5.0

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       10 non-null     int64
 1   Customer_Name  8 non-null      str
 2   Country        8 non-null      str
 3   Product        8 non-null      str
 4   Quantity       7 non-null      float64
 5   Price          8 non-null      float64
 6   Delivery_Days  7 non-null      float64
dtypes: float64(3), int64(1), str(3)
memory usage: 692.0 bytes

In [3]:
df.describe()

        Order_ID  Quantity        Price  Delivery_Days
count   10.00000  7.000000     8.000000       7.000000
mean   105.50000  2.142857  1012.500000       4.714286
std      3.02765  1.069045   412.093956       1.496026
min    101.00000  1.000000   600.000000       3.000000
25%    103.25000  1.500000   750.000000       3.500000
50%    105.50000  2.000000   800.000000       5.000000
75%    107.75000  2.500000  1500.000000       5.500000
max    110.00000  4.000000  1500.000000       7.000000

From the above, the average number of delivery days is 4.7 (almost 5).

In [4]:
df.isnull().sum()

Order_ID         0
Customer_Name    2
Country          2
Product          2
Quantity         3
Price            2
Delivery_Days    3
dtype: int64

From the above, the Order_ID is the only column without a null value

In [5]:
df.shape #For number of rows and columns

(10, 7)

In [6]:
df.head() #first five rows

   Order_ID Customer_Name  Country Product  Quantity   Price  Delivery_Days
0       101         Amara    Ghana  Laptop       2.0  1500.0            3.0
1       102          Bola  Nigeria   Phone       1.0   800.0            NaN
2       103           NaN    Kenya  Tablet       NaN   600.0            7.0
3       104         Diana      NaN  Laptop       3.0  1500.0            5.0
4       105          Efua    Ghana     NaN       2.0     NaN            3.0

In [7]:
df.tail() #last five rows

   Order_ID Customer_Name   Country Product  Quantity   Price  Delivery_Days
5       106        Fatima  Cameroon   Phone       NaN   800.0            NaN
6       107         Grace       NaN  Tablet       1.0   600.0            6.0
7       108           NaN     Kenya  Laptop       4.0  1500.0            NaN
8       109        Ifeoma   Nigeria     NaN       2.0     NaN            4.0
9       110         Joyce     Ghana   Phone       NaN   800.0            5.0

In [8]:
df['Customer_Name'] = df['Customer_Name'].fillna('Unknown')

In [9]:
print(df)

   Order_ID Customer_Name   Country Product  Quantity   Price  Delivery_Days
0       101         Amara     Ghana  Laptop       2.0  1500.0            3.0
1       102          Bola   Nigeria   Phone       1.0   800.0            NaN
2       103       Unknown     Kenya  Tablet       NaN   600.0            7.0
3       104         Diana       NaN  Laptop       3.0  1500.0            5.0
4       105          Efua     Ghana     NaN       2.0     NaN            3.0
5       106        Fatima  Cameroon   Phone       NaN   800.0            NaN
6       107         Grace       NaN  Tablet       1.0   600.0            6.0
7       108       Unknown     Kenya  Laptop       4.0  1500.0            NaN
8       109        Ifeoma   Nigeria     NaN       2.0     NaN            4.0
9       110         Joyce     Ghana   Phone       NaN   800.0            5.0

In [10]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())
df['Price'] = df['Price'].fillna(df['Price'].median())
df['Delivery_Days']=df['Delivery_Days'].fillna(df['Delivery_Days'].mean())
df['Country']=df['Country'].fillna('Unknown')
df['Product']=df['Product'].fillna('Unknown')
print(df)
#I chose median for price because the price values have more outliers

   Order_ID Customer_Name   Country  Product  Quantity   Price  Delivery_Days
0       101         Amara     Ghana   Laptop  2.000000  1500.0       3.000000
1       102          Bola   Nigeria    Phone  1.000000   800.0       4.714286
2       103       Unknown     Kenya   Tablet  2.142857   600.0       7.000000
3       104         Diana   Unknown   Laptop  3.000000  1500.0       5.000000
4       105          Efua     Ghana  Unknown  2.000000   800.0       3.000000
5       106        Fatima  Cameroon    Phone  2.142857   800.0       4.714286
6       107         Grace   Unknown   Tablet  1.000000   600.0       6.000000
7       108       Unknown     Kenya   Laptop  4.000000  1500.0       4.714286
8       109        Ifeoma   Nigeria  Unknown  2.000000   800.0       4.000000
9       110         Joyce     Ghana    Phone  2.142857   800.0       5.000000

In [11]:
df.isnull().sum()

Order_ID         0
Customer_Name    0
Country          0
Product          0
Quantity         0
Price            0
Delivery_Days    0
dtype: int64

It was hard deciding on whether to use the mean values for the delivery days and quantity. I had to check the Interquartile range of the values to see whether there were outliers or not.
I didn't drop the rows with the missing values for country and product because 20% of the dataset was at risk. These columns were also not key identifiers.